
server.port=8080
spring.cloud.gateway.server.webflux.default-filters=[0]=TokenRelay
spring.cloud.gateway.server.webflux.routes[0].id=Upload-Service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://Upload-Service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/upload/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1




eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-6ch632zxgjcyzrrq.us.auth0.com/

# OAuth2 Client for TokenRelay
spring.security.oauth2.client.registration.auth0.client-id=ghRhn8VBofni7Sr5gj764jtLEqadFyaT
spring.security.oauth2.client.registration.auth0.client-secret=xJhH6-_U7ogDGiuupXUbYjTimGXUD5rLGWpwudGN2ZEPXEBYDlYgbeSsEYGaC4W3
spring.security.oauth2.client.registration.auth0.provider=auth0
spring.security.oauth2.client.registration.auth0.client-name=Auth0
spring.security.oauth2.client.registration.auth0.redirect-uri=http://localhost:8080/login/oauth2/code/auth0
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email,offline_access

spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-6ch632zxgjcyzrrq.us.auth0.com/
spring.security.oauth2.client.provider.auth0.authorization-uri=https://dev-6ch632zxgjcyzrrq.us.auth0.com/authorize
spring.security.oauth2.client.provider.auth0.token-uri=https://dev-6ch632zxgjcyzrrq.us.auth0.com/oauth/token
spring.security.oauth2.client.provider.auth0.user-info-uri=https://dev-6ch632zxgjcyzrrq.us.auth0.com/userinfo
spring.security.oauth2.client.provider.auth0.jwk-set-uri=https://dev-6ch632zxgjcyzrrq.us.auth0.com/.well-known/jwks.json
